# Generated by Django 4.2.4 on 2023-11-16 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='region_id',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='id_region',
        ),
        migrations.DeleteModel(
            name='Region_Lista',
        ),
    ]
