# Generated by Django 4.2.6 on 2023-11-27 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='id_producto',
            field=models.ManyToManyField(related_name='ventas_id_producto', to='app.producto'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='productos',
            field=models.ManyToManyField(related_name='ventas_productos', to='app.producto'),
        ),
    ]
