# Generated by Django 4.2.6 on 2023-11-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_venta_id_producto_alter_venta_productos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='id_tipo_animal',
            new_name='tipo_animal',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='id_tipo_producto',
            new_name='tipo_producto',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='id_producto',
        ),
        migrations.AlterField(
            model_name='venta',
            name='productos',
            field=models.ManyToManyField(related_name='ventas', to='app.producto'),
        ),
    ]
