# Generated by Django 4.2.4 on 2023-11-18 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_rol_id_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dudas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=50)),
                ('duda', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
            ],
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='id_tipo_producto',
            new_name='tipo_producto',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='id_producto',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='id_tipo_producto',
        ),
        migrations.AddField(
            model_name='venta',
            name='producto',
            field=models.ForeignKey(default=99999, on_delete=django.db.models.deletion.CASCADE, to='app.producto'),
        ),
        migrations.AddField(
            model_name='venta',
            name='tipo_producto',
            field=models.ForeignKey(default=99999, on_delete=django.db.models.deletion.CASCADE, to='app.tipo_producto'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='rut_usuario',
            field=models.ForeignKey(default=99999, on_delete=django.db.models.deletion.CASCADE, to='app.usuario'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_animal',
            field=models.ForeignKey(default=99999, on_delete=django.db.models.deletion.CASCADE, to='app.tipo_animal'),
        ),
        migrations.AddField(
            model_name='venta',
            name='tipo_animal',
            field=models.ForeignKey(default=99999, on_delete=django.db.models.deletion.CASCADE, to='app.tipo_animal'),
        ),
    ]
