# Generated by Django 4.2.6 on 2023-11-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_venta_id_producto_alter_venta_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
