# Generated by Django 4.2.6 on 2023-12-04 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_producto_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_animal',
            name='tipo_producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.tipo_producto'),
            preserve_default=False,
        ),
    ]
